"""Lua script generation for GMod playermodel registration."""


def generate_playermodel_lua(model_name: str) -> str:
    """Generate a Lua script that registers a playermodel in GMod.

    The generated script is placed in ``lua/autorun/`` so that GMod
    executes it automatically on startup.  It performs three tasks:

    1. ``player_manager.AddValidModel`` – registers the model internally.
    2. ``list.Set("PlayerOptionsModel", ...)`` – shows it in the character
       selection screen.
    3. ``util.PrecacheModel`` (server-side) – preloads the model data for
       optimal multiplayer performance.

    Parameters
    ----------
    model_name : str
        Lowercase, underscore-separated model identifier
        (e.g. ``"quiple"``, ``"laguna"``).

    Returns
    -------
    str
        Complete Lua source code ready to write to a ``.lua`` file.
    """
    mdl_path = f"models/player/{model_name}/{model_name}.mdl"

    return (
        f'-- {model_name.capitalize()} Playermodel Registration\n'
        f'-- Auto-generated by VRM2GmodPlayermodel\n'
        f'\n'
        f'player_manager.AddValidModel("{model_name}", "{mdl_path}")\n'
        f'list.Set("PlayerOptionsModel", "{model_name}", "{mdl_path}")\n'
        f'\n'
        f'-- Precache on server\n'
        f'if SERVER then\n'
        f'    util.PrecacheModel("{mdl_path}")\n'
        f'end\n'
    )
