"""QC file generation operator with complete ValveBiped support.

Generates a production-quality QC file following the Althories guide convention
(no $definebone), including $bonemerge, $attachment, IK chains,
Proportion Trick, and complete $collisionjoints.

Reference: https://github.com/Althories/vrm-porting-guide-files
"""

import os
import bpy
from bpy.types import Operator

from ..data.bone_mapping import (
    BONEMERGE_BONES,
    ATTACHMENT_DEFS,
    IKCHAIN_DEFS,
    INCLUDEMODEL_PATHS_MALE,
    INCLUDEMODEL_PATHS_FEMALE,
)
from ..data.qc_templates import HITBOX_DEFS
from ..data.physics_presets import JOINT_CONSTRAINTS
from ..utils.bone_utils import find_armature


def _flex_controller_group(flex_name: str) -> str:
    """Return a flex controller group name for a given flex name."""
    if flex_name.startswith("blink") or flex_name.startswith("look_"):
        return "Eyes"
    if flex_name in ("aa", "ih", "ou", "ee", "oh"):
        return "Phoneme"
    return "Expressions"


class VRM2GMOD_OT_QCGenerate(Operator):
    bl_idname = "vrm2gmod.qc_generate"
    bl_label = "QC生成"
    bl_description = "Source Engineコンパイル用のQCファイルを生成（Althories guide準拠、Proportion Trick含む）"
    bl_options = {'REGISTER', 'UNDO'}

    @classmethod
    def poll(cls, context):
        return find_armature(context) is not None

    def execute(self, context):
        armature = find_armature(context)
        if not armature:
            self.report({'ERROR'}, "アーマチュアが見つかりません")
            return {'CANCELLED'}

        props = context.scene.vrm2gmod
        model_name = props.model_name.lower().replace(' ', '_')

        output_base = bpy.path.abspath(props.output_path)
        if not output_base:
            output_base = os.path.join(os.path.dirname(bpy.data.filepath or os.getcwd()),
                                       "vrm2gmod_output")

        compile_dir = os.path.join(output_base, "compile")
        os.makedirs(compile_dir, exist_ok=True)

        # Generate QC content
        qc_content = self._generate_qc(context, armature, model_name)

        # Write QC file
        qc_path = os.path.join(compile_dir, f"{model_name}.qc")
        with open(qc_path, 'w', encoding='utf-8') as f:
            f.write(qc_content)

        self.report({'INFO'}, f"QCファイル生成完了: {qc_path}")
        return {'FINISHED'}

    def _generate_qc(self, context, armature, model_name):
        """Generate the complete QC file content."""
        lines = []

        # Collect enabled flex items
        props = context.scene.vrm2gmod
        flex_names = []
        if props.export_flex:
            for item in props.flex_items:
                if item.flex_target == 'NONE':
                    continue
                if item.flex_target == 'CUSTOM':
                    if item.custom_flex_name:
                        flex_names.append(item.custom_flex_name)
                else:
                    flex_names.append(item.flex_target)

        # === Section 1: Header ===
        lines.append(f'// Auto-generated by VRM2GmodPlayermodel addon')
        lines.append(f'// Model: {model_name}')
        lines.append(f'')
        lines.append(f'$modelname "player/{model_name}/{model_name}.mdl"')
        lines.append(f'$cdmaterials "models/player/{model_name}/"')
        lines.append(f'$surfaceprop "flesh"')
        lines.append(f'')

        eye_height = self._calculate_eye_height(armature)
        lines.append(f'$eyeposition 0 0 {eye_height:.1f}')
        lines.append(f'')

        # === Section 2: $model with flexfile OR $bodygroup ===
        if flex_names:
            lines.append(f'$model "body" "{model_name}.smd" {{')
            lines.append(f'    flexfile "{model_name}_flex.vta" {{')
            lines.append(f'        defaultflex frame 0')
            for i, fname in enumerate(flex_names):
                lines.append(f'        flex "{fname}" frame {i + 1}')
            lines.append(f'    }}')
            lines.append(f'')
            for fname in flex_names:
                group = _flex_controller_group(fname)
                lines.append(
                    f'    flexcontroller {group} {fname} "range" 0 1')
            lines.append(f'')
            for fname in flex_names:
                lines.append(f'    %{fname} = {fname}')
            lines.append(f'}}')
        else:
            lines.append(f'$bodygroup "body"')
            lines.append(f'{{')
            lines.append(f'    studio "{model_name}.smd"')
            lines.append(f'}}')
        lines.append(f'')

        # === Section 3: $attachment ===
        for name, bone, ox, oy, oz, rx, ry, rz in ATTACHMENT_DEFS:
            lines.append(
                f'$attachment "{name}" "{bone}" '
                f'{ox:.1f} {oy:.1f} {oz:.1f} '
                f'rotate {rx:.1f} {ry:.1f} {rz:.1f}'
            )
        lines.append(f'')

        # === Section 4: $bonemerge ===
        for bone_name in BONEMERGE_BONES:
            lines.append(f'$bonemerge "{bone_name}"')
        lines.append(f'')

        # === Section 5: IK chains ===
        for chain_name, bone_name, kx, ky, kz in IKCHAIN_DEFS:
            lines.append(
                f'$ikchain "{chain_name}" "{bone_name}" '
                f'knee {kx:.3f} {ky:.3f} {kz:.3f}'
            )
        lines.append(f'')

        # === Section 6: IK autoplay lock ===
        lines.append(f'$ikautoplaylock "rfoot" 0.5 0.1')
        lines.append(f'$ikautoplaylock "lfoot" 0.5 0.1')
        lines.append(f'')

        # === Section 7: Ragdoll sequence ===
        # Must use "reference" (male_07 skeleton), NOT "proportions"!
        # The predelta autoplay adds (proportions − reference) to ALL sequences.
        # Using "proportions" causes double-adjustment:
        #   proportions + (proportions − reference) = 2×proportions − reference
        # Using "reference" gives correct result:
        #   reference + (proportions − reference) = proportions  ✓
        lines.append(f'$sequence "ragdoll" {{')
        lines.append(f'    "reference"')
        lines.append(f'    activity ACT_DIERAGDOLL 1')
        lines.append(f'    fadein 0.2')
        lines.append(f'    fadeout 0.2')
        lines.append(f'    fps 30')
        lines.append(f'    ikrule "rhand" release')
        lines.append(f'    ikrule "lhand" release')
        lines.append(f'    ikrule "rfoot" release')
        lines.append(f'    ikrule "lfoot" release')
        lines.append(f'}}')
        lines.append(f'')

        # === Section 8: $includemodel (HL2 animations) ===
        # Select animation set based on body_type
        body_type = props.body_type if props else 'MALE'
        include_paths = (INCLUDEMODEL_PATHS_FEMALE if body_type == 'FEMALE'
                         else INCLUDEMODEL_PATHS_MALE)
        lines.append(f'// Animation set: {body_type.lower()}')
        for path in include_paths:
            lines.append(f'$includemodel "{path}"')
        lines.append(f'')

        # === Section 9: Proportion Trick ★ MUST BE AFTER ALL $sequence/$include ===
        lines.append(f'// Proportion Trick')
        lines.append(f'//   reference.smd   = male_07 standard skeleton (HL2 citizen)')
        lines.append(f'//   proportions.smd = model actual skeleton')
        lines.append(f'//   delta = differences → adjusts HL2 animations to model proportions')
        lines.append(f'$animation a_reference "reference" fps 1')
        lines.append(f'$animation a_proportions "proportions" subtract a_reference 0')
        lines.append(f'$sequence proportions a_proportions predelta autoplay')
        lines.append(f'')

        # === Section 10: Hitboxes ===
        lines.append(f'$hboxset "default"')
        for group_id, bone_name, mins, maxs in HITBOX_DEFS:
            lines.append(
                f'$hbox {group_id} "{bone_name}" '
                f'{mins[0]} {mins[1]} {mins[2]} '
                f'{maxs[0]} {maxs[1]} {maxs[2]}'
            )
        lines.append(f'')

        # === Section 11: Collision joints ===
        lines.extend(self._generate_collision_block())
        lines.append(f'')

        return '\n'.join(lines) + '\n'

    def _generate_collision_block(self):
        """Generate the $collisionjoints QC block."""
        lines = []
        lines.append(f'$collisionjoints "physics.smd"')
        lines.append(f'{{')
        lines.append(f'    $mass 90.0')
        lines.append(f'    $inertia 10.0')
        lines.append(f'    $damping 0.01')
        lines.append(f'    $rotdamping 1.50')
        lines.append(f'    $rootbone "ValveBiped.Bip01_Pelvis"')
        lines.append(f'')

        for bone_name, min_x, max_x, min_y, max_y, min_z, max_z, friction in JOINT_CONSTRAINTS:
            lines.append(
                f'    $jointconstrain "{bone_name}" x limit {min_x:.1f} {max_x:.1f} 0.000'
            )
            lines.append(
                f'    $jointconstrain "{bone_name}" y limit {min_y:.1f} {max_y:.1f} 0.000'
            )
            lines.append(
                f'    $jointconstrain "{bone_name}" z limit {min_z:.1f} {max_z:.1f} 0.000'
            )
            lines.append(f'')

        lines.append(f'}}')

        # $collisiontext with jointmerge entries
        lines.append(f'')
        lines.append(f'$collisiontext')
        lines.append(f'{{')
        lines.append(f'    "break" "50.000000"')
        lines.append(f'    "animatedfriction"')
        lines.append(f'    {{')
        lines.append(f'        "animfrictionmin" "1.000000"')
        lines.append(f'        "animfrictionmax" "100.000000"')
        lines.append(f'        "animfrictiontimein" "0.500000"')
        lines.append(f'        "animfrictiontimeout" "0.300000"')
        lines.append(f'        "animfrictiontimehold" "0.000000"')
        lines.append(f'    }}')
        lines.append(f'    // Joint merges for simplified ragdoll')
        lines.append(f'    "jointmerge"')
        lines.append(f'    {{')
        lines.append(f'        "bonename" "ValveBiped.Bip01_R_Toe0"')
        lines.append(f'        "bonemerge" "ValveBiped.Bip01_R_Foot"')
        lines.append(f'    }}')
        lines.append(f'    "jointmerge"')
        lines.append(f'    {{')
        lines.append(f'        "bonename" "ValveBiped.Bip01_L_Toe0"')
        lines.append(f'        "bonemerge" "ValveBiped.Bip01_L_Foot"')
        lines.append(f'    }}')
        lines.append(f'}}')

        return lines

    def _calculate_eye_height(self, armature):
        """Calculate eye height from the armature's head bone position."""
        head_bone = armature.data.bones.get("ValveBiped.Bip01_Head1")
        if head_bone:
            head_pos = armature.matrix_world @ head_bone.head_local
            return head_pos.z + 2.0  # Slight offset above head bone

        # Fallback: estimate from armature bounds
        return 64.0  # Standard HL2 eye height


classes = (VRM2GMOD_OT_QCGenerate,)


def register():
    for cls in classes:
        bpy.utils.register_class(cls)


def unregister():
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)
